// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9FCwv9Be26F_y9-rhBcJ5S99BRdjBgEM',
    appId: '1:176474937232:web:5b6c7251a6c2b4f81c0515',
    messagingSenderId: '176474937232',
    projectId: 'routex-9205c',
    authDomain: 'routex-9205c.firebaseapp.com',
    storageBucket: 'routex-9205c.firebasestorage.app',
    measurementId: 'G-FQKYW4R92F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQBQO9s0PDFFPOTYzkMEXrcDaTgDQxjCk',
    appId: '1:176474937232:android:4dfe9ddfb2f554701c0515',
    messagingSenderId: '176474937232',
    projectId: 'routex-9205c',
    storageBucket: 'routex-9205c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrPhLqBacPIRdf0naWQbdBkQYwV79DbI',
    appId: '1:176474937232:ios:17f28990c84a3b8f1c0515',
    messagingSenderId: '176474937232',
    projectId: 'routex-9205c',
    storageBucket: 'routex-9205c.firebasestorage.app',
    iosBundleId: 'com.example.routexTesting',
  );

}