// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3EWGm3NyW2_l_n5OteGSHaOz4f9UL54',
    appId: '1:457771920138:web:3dc8377a612307c64a68f3',
    messagingSenderId: '457771920138',
    projectId: 'routex-app',
    authDomain: 'routex-app.firebaseapp.com',
    storageBucket: 'routex-app.firebasestorage.app',
    measurementId: 'G-QX2E3DNGC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjiHljXz4mmLF-dSsmlx3Dktegvpn7aPo',
    appId: '1:457771920138:android:facd095cd8eecc424a68f3',
    messagingSenderId: '457771920138',
    projectId: 'routex-app',
    storageBucket: 'routex-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVjM3KMp_6Bn0TxduIb9c9eX6bHO_Ls8w',
    appId: '1:457771920138:ios:1fe4e09fc1ca02ae4a68f3',
    messagingSenderId: '457771920138',
    projectId: 'routex-app',
    storageBucket: 'routex-app.firebasestorage.app',
    iosBundleId: 'com.example.routexApp',
  );
}
